POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "carlosdummy",
  "name": "carlos",
  "password": "passwordseguro"
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
}